config/routes.rb
Rails.application.routes.draw do
  resources :topics
  root 'topics#index'
  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :request_path
  def request_path #Viewでコントローラーごとに分岐
      @path = controller_path + '#' + action_name
      def @path.is(*str)
          str.map{|s| self.include?(s)}.include?(true)
      end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
  end

  def create
    comment = Comment.new(comment_params)
    comment.save
    redirect_to controller: "topics", action: "show", id: params[:comment][:topic_id]
  end

  private
  def comment_params
    params.require(:comment).permit(:agree, :user_name, :body, :topic_id)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
    @topic = Topic.new
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @comment = Comment.new
  end

  # GET /topics/new
  def new
    @topic = Topic.new #newアクションは呼び出されないかも・・
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to controller: "topics", action: "index", notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:user_name, :title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/application/_comment.html.erb
<% if comment.agree == false %>
  <div class="comment right">
    <p><span class="blue large">反対</span> <%= comment.user_name %>
    <span class="only_mobile_brank"><%= comment.created_at.to_s(:db) %></span></p>
    <div class="comment_body disagree">
      <h3>
        <%= comment.body %>
      </h3>
    </div>
  </div>
<% else %>
  <div class="comment left">
    <p><span class="red large">賛成</span> <%= comment.user_name %>
    <span class="only_mobile_brank"><%= comment.created_at.to_s(:db) %></span></p>
    <div class="comment_body agree">
      <h3>
        <%= comment.body %>
      </h3>
    </div>
  </div>
<% end %>

app/views/application/_comments.html.erb
<% if comments %>
  <% comments.each do |comment| %>
    <div class="comment_wrapper clearfix">
      <%= render 'application/comment', comment: comment %>
    </div>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %> <!-- checkがtrueならform送信 -->
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

  <% end %>

  <div class="field">
    <label><%= f.radio_button :agree, true %>賛成</label>
    <label><%= f.radio_button :agree, false %>反対</label>
  </div>
  <div class="field">
    <%= f.label "ユーザー名" %></br>
    <%= f.text_field :user_name, {:id => "user_name"} %> <!-- エンターキーで送信されないようにしたい -->
  </div>
  <div class="field">
    <%= f.label "コメント" %></br>
    <%= f.text_area :body, {:class => "text_field text_body", :id => "body"} %>
  </div>

  <%= f.hidden_field(:topic_id, value: topic_id) %>
  <div class="actions">
    <%= f.submit name="コメントする"%>
  </div>
<% end %>

app/views/comments/_modal_comment.html.erb
<!-- モーダルウィンドウを呼び出すボタン -->
<button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
  新規コメント
</button>

<!-- モーダルウィンドウの中身 -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">新規コメント</h4>
      </div>
      <div class="modal-body">
        <%= render 'comments/form', comment: @comment, topic_id: @topic.id %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/comments/index.html.erb
<%= render 'comments' %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">Place sticky footer content here.</p>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yboard|why?に対して気軽に対話できる場</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>

<div class="container">
    <header class="clearfix">
        <h1 class="left">
            <%= link_to "Yboard", root_path %>
        </h1>
        <div class="button_position right">
          <% if @path.is('topics#index') %> <!-- コントローラーごとに分岐 -->
            <%= render 'topics/modal_new' %>
          <% elsif @path.is('topics#show') %>
            <%= render 'comments/modal_comment' %>
          <% end %>
        </div>
    </header>
</div>
<hr>

<%= yield %>

<hr>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/topics/_form.html.erb
<%= form_for(topic, :html =>  {:onsubmit => "return check();"} ) do |f| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "ユーザー名" %></br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label "タイトル" %></br>
    <%= f.text_field :title, {:class => "text_field"} %>
  </div>
  <div class="field">
    <%= f.label "本文" %></br>
    <%= f.text_area :body, {:class => "text_field text_body"} %>
  </div>
  <div class="actions">
    <%= f.submit name="新規投稿"%>
  </div>
<% end %>

app/views/topics/_modal_new.html.erb
<!-- モーダルウィンドウを呼び出すボタン -->
<button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
  <!-- <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <!-- プラスアイコン -->
  新規投稿
</button>

<!-- モーダルウィンドウの中身 -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">新規投稿</h4>
      </div>
      <div class="modal-body">
        <%= render 'topics/form', topic: @topic %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/topics/_new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to '一覧へ', topics_path %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="jumbotron">
  <div class="container">
    <h1>Whyを共有しよう</h1>
    <p>
      ここは気軽に意見交換・対話できる場です。
    </br>その際には、"賛成"もしくは"反対"を明確にしてコメントしてください。
    </p>
  </div>
</div>

<div class="container">
  <% @topics.each do |topic| %>
  <div class="topic_index">
    <ul>
      <li>
        <h2 class="title"><%= link_to "#{topic.title}", topic %></h2>
      </li>
      <li>
        <p><%= truncate(topic.body, length: 80, omission: '...') %></p>
      </li>
      <li>
        <p>
          投稿者名: <%= topic.user_name %> <%= topic.created_at.to_s(:db) %>
        </p>
      </li>
    </ul>
  </div>
  <% end %>
</div> <!-- container -->

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to '一覧へ', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="topic_show clearfix">
    <h2 class="title">
      <%= @topic.title %>
    </h2>
    <h3 class="body">
      <%= @topic.body %>
    </h3>
    <p class="right">
      投稿者名：<%= @topic.user_name %>
      <%= @topic.created_at.to_s(:db) %>
    </p>
  </div>

  <hr>

  <div class="comment_container">
    <%= render 'application/comments', comments: @topic.comments %>
  </div>
</div>